### ISSUE TITLE
Add post dump hooks

### ISSUE THREAD

**Issue by h-bragg** [graze/sprout#10]
- Allow for a custom command to be run after something is dumped
  - This could (for example) attempt to remove rows with a deleted field set

You should be able to define formats the hooks are called on.

Potential config:

```yaml
hooks:
  - type: post_dump 
    format: sql
    command: /path/to/runnable/file
```
